name: symfony-blog
recipe: symfony
config:
  webroot: ./public
  via: nginx
  php: '8.1'
  xdebug: true

proxy:
  #APACHE
  #  appserver:
  #    - dev.primes-energies.leclerc
  #NGINX
  appserver_nginx:
    - symblog.lndo.site

services:
  # Container databases
  database:
    portforward: 3310
    creds:
      user: symblog_user
      password: symblog_pass
      database: symblog_db

  # Container Node
  node:
    type: node
    install_dependencies_as_root:
      # Upgrade Yarn
      - "curl -o- -L https://yarnpkg.com/install.sh | bash"
    install_dependencies_as_me:
      - "yarn --cwd=$LANDO_MOUNT"

tooling:
  #  NGINX VERSION
  xdebug-on:
    service: appserver
    description: Enable xdebug for nginx.
    cmd: docker-php-ext-enable xdebug && pkill -o -USR2 php-fpm
    user: root

  xdebug-off:
    service: appserver
    description: Disable xdebug for nginx.
    cmd: rm /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini && pkill -o -USR2 php-fpm
    user: root

# Symfony console
  sf:
    service: appserver
    description: Run Symfony console commands
    cmd: php bin/console
  diff:
    service: appserver
    description: Generate a database migration by comparing your current database to your mapping information
    cmd: php bin/console doctrine:migrations:diff
  migrate:
    service: appserver
    description: Execute a database migration to a specified version or the latest available version
    cmd: php bin/console doctrine:migrations:migrate
  cache:
    service: appserver
    description: Clears the Symfony cache
    cmd: php bin/console cache:clear
  ## —— 📊 Database ——
  database-init: ## Init database
    service: appserver
    cmd:
    - php bin/console d:d:d --force --if-exists
    - php bin/console d:d:d --force --if-exists
    - php bin/console d:m:m --no-interaction
    - php bin/console d:f:l --no-interaction

  database-drop: ## Create database
    service: appserver
    cmd: php bin/console d:d:d --force --if-exists

  database-create: ## Create database
    service: appserver
    cmd: php bin/console d:d:c --if-not-exists

  database-remove: ## Drop database
    service: appserver
    cmd: php bin/console d:d:d --force --if-exists

  database-migration: ## Make migration
    service: appserver
    cmd: php bin/console make:migration

  database-migrate: ## Migrate migrations
    service: appserver
    cmd: php bin/console d:m:m --no-interaction

  database-fixtures-load: ## Load fixtures
    service: appserver
    cmd: php bin/console d:f:l --no-interaction

  # Node tooltips
  yarn:
    service: node
    description: Run the Yarn package manager
    cmd: yarn


## —— ✅ Test ——
  tests: ## Run all tests
    service: appserver
    cmd:
      - php bin/console d:d:d --force --if-exists --env=test
      - php bin/console d:d:c --env=test
      - php bin/console d:m:m --no-interaction --env=test
      - php bin/console d:f:l --no-interaction --env=test
      - php bin/phpunit --testdox tests/Unit/
      - php bin/phpunit --testdox tests/Functional/
      - php bin/phpunit --testdox tests/E2E/

  database-init-test: ## Init database for test
    service: appserver
    cmd:
    - php bin/console d:d:d --force --if-exists --env=test
    - php bin/console d:d:c --env=test
    - php bin/console d:m:m --no-interaction --env=test
    - php bin/console d:f:l --no-interaction --env=test
